# Generated by Django 3.1.4 on 2020-12-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('Bisbn', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='ISBN')),
                ('Bname', models.CharField(max_length=40, verbose_name='书名')),
                ('Bauthor', models.CharField(max_length=40, verbose_name='作者')),
                ('Bprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('Bcategory', models.CharField(max_length=10, verbose_name='类别')),
                ('Bpublisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('Bpublisherdate', models.DateField(null=True, verbose_name='出版日期')),
                ('Bintroduction', models.TextField(verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmanager',
            fields=[
                ('Mid', models.AutoField(primary_key=True, serialize=False, verbose_name='工号')),
                ('Mpassword', models.CharField(max_length=15, verbose_name='密码')),
                ('Mrealname', models.CharField(max_length=40, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'ordering': ['Mid'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Coid', models.AutoField(primary_key=True, serialize=False, verbose_name='留言编号')),
                ('Cocontent', models.TextField(verbose_name='留言内容')),
                ('Cograde', models.PositiveIntegerField(verbose_name='评分')),
                ('Cobook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Commentbook', to='bookseller.book')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('Vphone', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='电话')),
                ('Vusername', models.CharField(max_length=40, verbose_name='用户名')),
                ('Vpassword', models.CharField(max_length=15, verbose_name='密码')),
                ('Vrealname', models.CharField(max_length=40, verbose_name='姓名')),
                ('Vsex', models.CharField(choices=[('Man', '男'), ('Woman', '女')], max_length=10, verbose_name='性别')),
                ('Vemail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('Vaddress', models.CharField(max_length=60, verbose_name='地址')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
        migrations.CreateModel(
            name='Commentlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recontent', models.TextField(verbose_name='留言回复')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='bookseller.comment')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager', to='bookseller.bookmanager')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Covip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Commentvip', to='bookseller.vip'),
        ),
        migrations.CreateModel(
            name='Shoppingcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.PositiveIntegerField(verbose_name='编号')),
                ('Cnumber', models.PositiveIntegerField(verbose_name='数量')),
                ('Cprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价')),
                ('Cbook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Shoppingbook', to='bookseller.book')),
                ('Cvip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Shoppingvip', to='bookseller.vip')),
            ],
            options={
                'unique_together': {('Cid', 'Cbook')},
            },
        ),
        migrations.CreateModel(
            name='Sellrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.PositiveIntegerField(verbose_name='订单号')),
                ('Snumber', models.PositiveIntegerField(verbose_name='销售数量')),
                ('Sprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='单价')),
                ('Sdate', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('Sbook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sellbook', to='bookseller.book')),
                ('Svip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sellvip', to='bookseller.vip')),
            ],
            options={
                'unique_together': {('Sid', 'Sbook')},
            },
        ),
    ]
